ResultProcessor/Models/ScoreSheet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ResultProcessor.Models
{
    public class ScoreSheet
    {
        public int Id { get; set; }
        [Required()]
        [Display(Name ="Reg No")]
        public string RegNo { get; set; }
        [Required]
        [Display(Name ="Course")]
        public int CourseId { get; set; }
        public int Score { get; set; }
        public string Semester { get; set; }
        public string Level { get; set; }
        public char Grade { get; set; }
        public DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public string Session { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedDate { get; set; }
        
        public virtual Course Course { get; set; }
        //public virtual Student Student { get; set; }
        
    }
}

ResultProcessor/Controllers/ScoreSheetsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using ResultProcessor.Data;
using ResultProcessor.Models;

namespace ResultProcessor.Controllers
{
    [Authorize(Roles="Admin,Lecturer")]
    public class ScoreSheetsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IHostingEnvironment _hostingEnvironment;

        public ScoreSheetsController(ApplicationDbContext context,SignInManager<IdentityUser> signInManager,UserManager<IdentityUser> userManager, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Import()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Import(IFormFile file)
        {
            string rootFolder = _hostingEnvironment.WebRootPath;
            
            //string fileName = file.FileName;
            string fileName = @"CourseTest.xlsx";// file.FileName;
            //FileInfo fileInfo = new FileInfo(fileName);
            FileInfo fileInfo = new FileInfo(Path.Combine(rootFolder, fileName));

            using (var package=new ExcelPackage(fileInfo))
            {
                var dateCreated = DateTime.Now;
                var enteredBy = User.Identity.Name;
                var excelWorkSheet = package.Workbook.Worksheets["Sheet1"];
                //var excelWorkSheet = package.Workbook.Worksheets[0];
                int totalRows = excelWorkSheet.Dimension.Rows;
                var scoreSheets = new List<ScoreSheet>();
                for (int i = 2; i <= totalRows; i++)
                {
                    scoreSheets.Add(new ScoreSheet
                    {
                        RegNo = excelWorkSheet.Cells[i, 1].Value.ToString(),
                        CourseId =int.Parse( excelWorkSheet.Cells[i, 2].Value.ToString()),
                        Score=int.Parse(excelWorkSheet.Cells[i,3].Value.ToString()),
                        Semester= excelWorkSheet.Cells[i,4].Value.ToString(),
                        Level=excelWorkSheet.Cells[i,5].Value.ToString(),
                        Grade=Utility.GetGrade(int.Parse(excelWorkSheet.Cells[i, 3].Value.ToString())),
                        DateEntered=dateCreated,
                        EnteredBy=enteredBy

                    });
                }
               await _context.ScoreSheet.AddRangeAsync(scoreSheets);
              await  _context.SaveChangesAsync();

            }
            return Redirect("Index");
        }

        // GET: ScoreSheets
        public async Task<IActionResult> Index()
        {
            if (_signInManager.IsSignedIn(User))
            {
                var currentUser = await _userManager.GetUserAsync(User);
                var isAdmin = currentUser != null && await _userManager.IsInRoleAsync(currentUser, Constants.Administrator);

                if (isAdmin)
                {
                    var user = HttpContext.User.Identity.Name;
                    //UserManager<IdentityUser>
                    var applicationDbContext = _context.ScoreSheet.Include(s => s.Course);
                    return View(await applicationDbContext.ToListAsync());
                }
                else
                {
                    var user = HttpContext.User.Identity.Name;
                    //UserManager<IdentityUser>
                    var applicationDbContext = _context.ScoreSheet.Include(s => s.Course).Where(c => c.EnteredBy == user || c.ModifiedBy == user);
                    return View(await applicationDbContext.ToListAsync());
                }
            }
            return View();
            
        }
        private async Task<List<string>> GetRegNo()
        {
            List<string> regNo = new List<string>();

            var dbRegNo = await (from reg in _context.Student select reg.RegNo).ToListAsync();

            foreach (var item in dbRegNo)
            {
                regNo.Add(item);
            }
            return regNo;
        }


        // GET: ScoreSheets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scoreSheet = await _context.ScoreSheet
                .Include(s => s.Course)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (scoreSheet == null)
            {
                return NotFound();
            }

            return View(scoreSheet);
        }

        // GET: ScoreSheets/Create
        public IActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Title");
            ViewData["RegNo"] = new SelectList(_context.Student, "RegNo", "RegNo");

            var Semester = new List<SelectListItem>
                {
                    new SelectListItem {Text = "First", Value = "First"},
                    new SelectListItem {Text = "Second", Value = "Second"}
                };

            ViewBag.Semester = Semester;
            var level = new List<SelectListItem>
            {
                new SelectListItem {Text="level I", Value = "level I"},
                new SelectListItem {Text="level II", Value = "level II"},
                new SelectListItem {Text="level III", Value = "level III"},
                new SelectListItem {Text="level IV", Value = "level IV"},
                new SelectListItem {Text="level V", Value = "level V"},
                new SelectListItem {Text="level SPILL I", Value = "level SPILL I"},
                new SelectListItem {Text="level SPILL II", Value = "level SPILL II"}
            };
            ViewBag.Level = level;
            var Sessions = new List<SelectListItem>
            {
                new SelectListItem {Text="2018/2019", Value = "2018/2019"},
                new SelectListItem {Text="2019/2020", Value = "2019/2020"},
                new SelectListItem {Text="2020/2021", Value = "2020/2021"},
                new SelectListItem {Text="2021/2022", Value = "2021/2022"},
                new SelectListItem {Text="2022/2023", Value = "2022/2023"},
                new SelectListItem {Text="2023/2024", Value = "2023/2024"},
                new SelectListItem {Text="2024/2025", Value = "2024/2025"}
            };
            ViewBag.Sessions = Sessions;
            return View();
        }

        // POST: ScoreSheets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RegNo,CourseId,Score,Semester,Session,Level,Grade,DateEntered,EnteredBy,ModifiedBy,ModifiedDate")] ScoreSheet scoreSheet)
        {
            if (ModelState.IsValid)
            {
                var createdBy = User.Identity.Name;
                var dateCreated = DateTime.Now;
                scoreSheet.EnteredBy = createdBy;
                scoreSheet.DateEntered = dateCreated;
                scoreSheet.Grade = Utility.GetGrade(scoreSheet.Score);
                _context.Add(scoreSheet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Title", scoreSheet.CourseId);
            return View(scoreSheet);
        }

        // GET: ScoreSheets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scoreSheet = await _context.ScoreSheet.FindAsync(id);
            if (scoreSheet == null)
            {
                return NotFound();
            }
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Title", scoreSheet.CourseId);
            ViewData["RegNo"] = new SelectList(_context.Student, "RegNo", "RegNo");
            return View(scoreSheet);
        }

        // POST: ScoreSheets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RegNo,CourseId,Score,Semester,Session,Level,Grade,DateEntered,EnteredBy,ModifiedBy,ModifiedDate")] ScoreSheet scoreSheet)
        {
            if (id != scoreSheet.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var createdBy = User.Identity.Name;
                    var dateCreated = DateTime.Now;
                    scoreSheet.ModifiedBy = createdBy;
                    scoreSheet.ModifiedDate = dateCreated;
                    scoreSheet.Grade = Utility.GetGrade(scoreSheet.Score);
                    _context.Update(scoreSheet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScoreSheetExists(scoreSheet.Id))
                    {
                        return NotFound();

ResultProcessor/Views/ScoreSheets/Create.cshtml
@model ResultProcessor.Models.ScoreSheet

@{
    ViewData["Title"] = "Create";
}

<h2>Enter Score Sheet</h2>

<div class="pull-right">
    <a href="@Url.Action("Import")">Import From Excel File<i class="glyphicon glyphicon-import"></i></a>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create"> 
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RegNo" class="control-label"></label>
                @*<input asp-for="RegNo" class="form-control" />*@
                <select asp-for="RegNo" class="form-control" asp-items="ViewBag.RegNo"></select>
                <span asp-validation-for="RegNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class ="form-control" asp-items="ViewBag.CourseId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Score" class="control-label"></label>
                <input asp-for="Score" class="form-control" />
                <span asp-validation-for="Score" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <select asp-for="Semester" asp-items="(List<SelectListItem>)ViewBag.Semester" class="form-control"></select>
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Level" class="control-label"></label>
                <select asp-for="Level" asp-items="(List<SelectListItem>)ViewBag.Level" class="form-control"></select>
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Session" class="control-label"></label>
                <select asp-for="Session" asp-items="(List<SelectListItem>)ViewBag.Sessions" class="form-control"></select>
                <span asp-validation-for="Session" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Enter" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

ResultProcessor/Views/ScoreSheets/Delete.cshtml
@model ResultProcessor.Models.ScoreSheet

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ScoreSheet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RegNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RegNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Session)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Session)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Level)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Level)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Course.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-primary" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ResultProcessor/Views/ScoreSheets/Details.cshtml
@model ResultProcessor.Models.ScoreSheet

@{
    ViewData["Title"] = "Details";
}

<h2>Score Sheet Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RegNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RegNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Level)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Level)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Session)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Session)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Course.Title)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ResultProcessor/Views/ScoreSheets/Edit.cshtml
@model ResultProcessor.Models.ScoreSheet

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>ScoreSheet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="RegNo" class="control-label"></label>
                @*<input asp-for="RegNo" class="form-control" />*@
                <select asp-for="RegNo" class="form-control" asp-items="ViewBag.RegNo"></select>
                <span asp-validation-for="RegNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseId"></select>
                <span asp-validation-for="CourseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Score" class="control-label"></label>
                <input asp-for="Score" class="form-control" />
                <span asp-validation-for="Score" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <select asp-for="Semester" asp-items="(List<SelectListItem>)ViewBag.Semester" class="form-control"></select>
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Level" class="control-label"></label>
                <select asp-for="Level" asp-items="(List<SelectListItem>)ViewBag.Level" class="form-control"></select>
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Session" class="control-label"></label>
                <select asp-for="Session" asp-items="(List<SelectListItem>)ViewBag.Sessions" class="form-control"></select>
                <span asp-validation-for="Session" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ResultProcessor/Views/ScoreSheets/Import.cshtml
<br />
<br />
<br />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="ScoreSheets" asp-action="Import" enctype="multipart/form-data" method="post">
            @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
            <div class="form-group">
               <input type="file"name="file" class="form-control"/>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

ResultProcessor/Views/ScoreSheets/Index.cshtml
@model IEnumerable<ResultProcessor.Models.ScoreSheet>

@{
    ViewData["Title"] = "Index";
}

<h2>Score Sheet Collections</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RegNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Score)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Session)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Level)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grade)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RegNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Score)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Session)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Level)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Course.Title)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>